# Generated by Django 2.2.24 on 2021-10-03 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=50)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='shop/default1.jpg', height_field=50, upload_to='shop/', width_field=50)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('area', models.TextField()),
                ('about', models.TextField()),
                ('item_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
            ],
        ),
    ]
