# Generated by Django 2.2.24 on 2021-10-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='shop/default1.jpg', height_field='image_height', upload_to='shop/', width_field='image_width'),
        ),
    ]
