# Generated by Django 2.2.24 on 2021-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211003_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(default=10),
        ),
    ]
