# Generated by Django 2.2.24 on 2021-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211003_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category.default2.jpg', upload_to='category/'),
        ),
    ]
