# Generated by Django 2.2.24 on 2021-10-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orderplaced_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='items',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
